"""
TITLE: Zero-Knowledge Proofs (Schnorr Protocol & R1CS)
CATEGORY: core

WHAT THIS IMPLEMENTS:
    Two fundamental ZK proof systems from scratch. Part 1 implements the Schnorr
    sigma protocol — an interactive proof where a prover demonstrates knowledge of
    a discrete logarithm (secret key) without revealing it. Part 2 implements a
    simplified R1CS (Rank-1 Constraint System) that proves knowledge of a secret
    satisfying an arithmetic circuit.

KEY CONCEPTS:
    - Schnorr sigma protocol (commit → challenge → response)
    - Zero-knowledge: verifier learns nothing beyond the statement's truth
    - Soundness: a cheating prover cannot convince the verifier
    - R1CS (Rank-1 Constraint System) for arithmetic circuit satisfiability

PREREQUISITE SCRIPTS:
    - core/fundamentals/02_public_key_crypto.py (EC math, scalar multiplication)
    - core/fundamentals/03_digital_signatures.py (signing concepts)

REAL-WORLD RELEVANCE:
    ZK proofs are the foundation of privacy-preserving blockchains (Zcash, Tornado
    Cash), ZK-rollups (zkSync, StarkNet, Polygon zkEVM), and identity systems
    where you prove properties about data without revealing the data itself.
"""

import hashlib
import random

# ============================================================================
# SECTION 1: CONSTANTS AND CONFIGURATION
# ============================================================================

# secp256k1 curve parameters — same curve as Bitcoin/Ethereum
# Curve equation: y² = x³ + 7 (mod P)
P = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFFFFFC2F
A = 0  # secp256k1 coefficient a
B = 7  # secp256k1 coefficient b

# Generator point G
GX = 0x79BE667EF9DCBBAC55A06295CE870B07029BFCDB2DCE28D959F2815B16F81798
GY = 0x483ADA7726A3C4655DA4FBFC0E1108A8FD17B448A68554199C47D08FFB10D4B8
G = (GX, GY)

# Group order — number of points generated by G
N = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141

# Identity point (point at infinity)
IDENTITY = None

# Prime for R1CS finite field arithmetic (a 128-bit prime for manageable demo)
R1CS_PRIME = 2**127 - 1  # Mersenne prime, large enough for our circuits

# ============================================================================
# SECTION 2: IMPLEMENTATION
# ============================================================================

# ----------------------------------------------------------------------------
# Elliptic curve primitives (copied from core/fundamentals/02_public_key_crypto.py)
# Each script must be self-contained, so we include the EC math here.
# ----------------------------------------------------------------------------

def mod_inverse(a: int, m: int) -> int:
    """Modular inverse via Fermat's little theorem: a^(m-2) mod m."""
    return pow(a, m - 2, m)


def point_add(p1: tuple | None, p2: tuple | None) -> tuple | None:
    """Add two points on secp256k1. Returns None for identity."""
    if p1 is IDENTITY:
        return p2
    if p2 is IDENTITY:
        return p1

    x1, y1 = p1
    x2, y2 = p2

    if x1 == x2 and y1 != y2:  # Inverse points → identity
        return IDENTITY

    if x1 == x2 and y1 == y2:  # Same point → use doubling
        return point_double(p1)

    # Slope through two distinct points
    s = ((y2 - y1) * mod_inverse(x2 - x1, P)) % P
    x3 = (s * s - x1 - x2) % P
    y3 = (s * (x1 - x3) - y1) % P
    return (x3, y3)


def point_double(point: tuple | None) -> tuple | None:
    """Double a point (tangent line intersection)."""
    if point is IDENTITY:
        return IDENTITY
    x, y = point
    if y == 0:
        return IDENTITY
    # Tangent slope: (3x² + A) / (2y), A=0 for secp256k1
    s = ((3 * x * x + A) * mod_inverse(2 * y, P)) % P
    x3 = (s * s - 2 * x) % P
    y3 = (s * (x - x3) - y) % P
    return (x3, y3)


def scalar_multiply(k: int, point: tuple | None) -> tuple | None:
    """Multiply point by scalar using double-and-add (O(log k) steps)."""
    if k == 0 or point is IDENTITY:
        return IDENTITY
    k = k % N
    result = IDENTITY
    addend = point
    while k > 0:
        if k & 1:
            result = point_add(result, addend)
        addend = point_double(addend)
        k >>= 1
    return result


# ----------------------------------------------------------------------------
# Part 1: Schnorr Sigma Protocol
# ----------------------------------------------------------------------------
# The Schnorr protocol proves knowledge of x such that X = x*G,
# without revealing x. It's a 3-step interactive protocol:
#   1. Prover commits: pick random r, send R = r*G
#   2. Verifier challenges: send random c
#   3. Prover responds: send s = r + c*x (mod N)
# Verifier checks: s*G == R + c*X
# Why it works: if s*G = (r + c*x)*G = r*G + c*x*G = R + c*X

class SchnorrProver:
    """Prover who knows secret x and wants to prove knowledge of it."""

    def __init__(self, secret: int):
        self.x = secret  # The secret discrete log
        self.X = scalar_multiply(secret, G)  # Public key X = x*G
        self._r = None  # Nonce, stored between commit and respond steps

    def commit(self) -> tuple:
        """Step 1: Pick random nonce r, return commitment R = r*G.

        The randomness r is critical — reusing it would leak the secret,
        just like nonce reuse in ECDSA (the PS3 hack).
        """
        self._r = random.SystemRandom().randint(1, N - 1)
        R = scalar_multiply(self._r, G)  # Commitment point
        return R

    def respond(self, challenge: int) -> int:
        """Step 3: Compute response s = r + c*x (mod N).

        This cleverly combines the nonce and secret so that the verifier
        can check the relationship without learning either value.
        """
        s = (self._r + challenge * self.x) % N
        self._r = None  # Clear nonce to prevent reuse
        return s


class SchnorrVerifier:
    """Verifier who checks the proof without learning the secret."""

    def __init__(self, public_key: tuple):
        self.X = public_key  # The public key X = x*G

    def challenge(self) -> int:
        """Step 2: Generate a random challenge c.

        The challenge must be unpredictable — if the prover could predict it,
        they could fake a proof without knowing x.
        """
        return random.SystemRandom().randint(1, N - 1)

    def verify(self, R: tuple, c: int, s: int) -> bool:
        """Check: s*G == R + c*X.

        If s = r + c*x, then:
            s*G = (r + c*x)*G = r*G + c*(x*G) = R + c*X
        A cheater who doesn't know x cannot produce a valid s for a random c.
        """
        lhs = scalar_multiply(s, G)        # s*G
        cX = scalar_multiply(c, self.X)     # c*X
        rhs = point_add(R, cX)             # R + c*X
        return lhs == rhs


def run_schnorr_protocol(secret: int) -> dict:
    """Run the full 3-step Schnorr protocol and return all values."""
    prover = SchnorrProver(secret)
    verifier = SchnorrVerifier(prover.X)

    # Step 1: Prover commits
    R = prover.commit()

    # Step 2: Verifier sends challenge
    c = verifier.challenge()

    # Step 3: Prover responds
    s = prover.respond(c)

    # Verification
    valid = verifier.verify(R, c, s)

    return {
        "public_key": prover.X,
        "R": R,
        "challenge": c,
        "response": s,
        "valid": valid,
    }


# ----------------------------------------------------------------------------
# Part 2: Simplified R1CS (Rank-1 Constraint System)
# ----------------------------------------------------------------------------
# R1CS encodes arithmetic circuits as a system of constraints of the form:
#     (a · w) * (b · w) = (c · w)
# where w is the "witness" vector and a, b, c are coefficient vectors.
#
# Example: proving x*x + x = 42 (i.e., x² + x - 42 = 0, solution x=6)
# We flatten this into:
#   Gate 1: v1 = x * x         →  a=[0,1,0], b=[0,1,0], c=[0,0,1]
#   Gate 2: out = v1 + x       →  a=[0,1,1], b=[1,0,0], c=[42,0,0]
# Witness: w = [1, x, v1]  (where index 0 is the constant "1")

FP = R1CS_PRIME  # Shorthand for the field prime


def fp_mod(x: int) -> int:
    """Reduce x modulo the field prime."""
    return x % FP


def dot_product(a: list[int], b: list[int]) -> int:
    """Compute dot product of two vectors over GF(FP)."""
    result = 0
    for ai, bi in zip(a, b):
        result = (result + ai * bi) % FP
    return result


class R1CSCircuit:
    """A simple R1CS circuit with constraints of the form (a·w)*(b·w) = (c·w).

    Each constraint is a "gate" in the arithmetic circuit. The circuit is
    satisfiable if there exists a witness w that makes all constraints hold.
    """

    def __init__(self):
        self.constraints = []  # List of (a, b, c) tuples
        self.num_vars = 0      # Number of variables (including constant 1)

    def add_constraint(self, a: list[int], b: list[int], c: list[int]):
        """Add a constraint: (a·w) * (b·w) = (c·w)."""
        self.constraints.append((a, b, c))
        # Track the number of variables from the longest vector
        self.num_vars = max(self.num_vars, len(a), len(b), len(c))

    def is_satisfied(self, witness: list[int]) -> tuple[bool, list[bool]]:
        """Check if the witness satisfies all constraints.

        Returns (all_satisfied, per_constraint_results).
        """
        results = []
        for a, b, c in self.constraints:
            # Pad vectors to witness length if needed
            a_padded = a + [0] * (len(witness) - len(a))
            b_padded = b + [0] * (len(witness) - len(b))
            c_padded = c + [0] * (len(witness) - len(c))

            # Compute (a·w) * (b·w) and compare to (c·w)
            left = dot_product(a_padded, witness)
            right = dot_product(b_padded, witness)
            out = dot_product(c_padded, witness)

            product = (left * right) % FP
            results.append(product == out)

        return (all(results), results)


def build_quadratic_circuit() -> tuple[R1CSCircuit, int]:
    """Build an R1CS circuit for: x² + x = 42 (solution: x = 6).

    Flattening into rank-1 constraints:
      Witness vector: w = [1, x, v1]
        Index 0: constant 1 (always present in R1CS)
        Index 1: x (the secret input)
        Index 2: v1 = x * x (intermediate variable)

      Gate 1: v1 = x * x
        a = [0, 1, 0]  →  a·w = x
        b = [0, 1, 0]  →  b·w = x
        c = [0, 0, 1]  →  c·w = v1
        Check: x * x = v1

      Gate 2: v1 + x = 42
        Rewrite as: (v1 + x) * 1 = 42
        a = [0, 1, 1]  →  a·w = x + v1
        b = [1, 0, 0]  →  b·w = 1
        c = [42, 0, 0] →  c·w = 42
        Check: (v1 + x) * 1 = 42
    """
    circuit = R1CSCircuit()

    # Gate 1: x * x = v1
    circuit.add_constraint(
        a=[0, 1, 0],  # selects x
        b=[0, 1, 0],  # selects x
        c=[0, 0, 1],  # selects v1
    )

    # Gate 2: (v1 + x) * 1 = 42
    circuit.add_constraint(
        a=[0, 1, 1],  # selects x + v1
        b=[1, 0, 0],  # selects constant 1
        c=[42, 0, 0], # selects 42 (= 42 * 1)
    )

    # The answer is x=6: 6*6 + 6 = 42
    answer = 6
    return circuit, answer


def build_witness(x: int) -> list[int]:
    """Build a witness vector for the quadratic circuit given input x.

    Witness: [1, x, x*x]
    The prover computes all intermediate values honestly.
    """
    v1 = fp_mod(x * x)  # Intermediate: v1 = x²
    return [1, fp_mod(x), v1]


# ============================================================================
# SECTION 3: DEMONSTRATION
# ============================================================================

def _hex_short(n: int, length: int = 16) -> str:
    """Format a large integer as a short hex string."""
    h = f"{n:064x}"
    if len(h) > length:
        return f"0x{h[:length//2]}...{h[-length//2:]}"
    return f"0x{h}"


def demo():
    """Run a visual demonstration of zero-knowledge proofs."""

    print("=" * 70)
    print("  Zero-Knowledge Proofs — Schnorr Protocol & R1CS")
    print("=" * 70)

    # -----------------------------------------------------------------------
    # Part 1: Schnorr Sigma Protocol
    # -----------------------------------------------------------------------
    print("\n" + "=" * 70)
    print("  PART 1: Schnorr Sigma Protocol")
    print("  (Prove knowledge of a secret key without revealing it)")
    print("=" * 70)

    print("\n--- Protocol Overview ---\n")
    print("  ┌──────────────────────────────────────────────────────────┐")
    print("  │  PROVER (knows x)              VERIFIER (knows X=x*G)  │")
    print("  │                                                         │")
    print("  │  1. Pick random r               .                       │")
    print("  │     Compute R = r*G             .                       │")
    print("  │              ───── R ─────>                              │")
    print("  │                                                         │")
    print("  │  .                  2. Pick random challenge c          │")
    print("  │              <──── c ──────                              │")
    print("  │                                                         │")
    print("  │  3. Compute s = r + c*x          .                      │")
    print("  │              ───── s ─────>                              │")
    print("  │                                                         │")
    print("  │  .                  4. Check: s*G == R + c*X            │")
    print("  └──────────────────────────────────────────────────────────┘")

    # --- Run the protocol with a real secret ---
    print("\n--- Running Schnorr Protocol ---\n")

    # Generate a secret key
    secret = random.SystemRandom().randint(1, N - 1)
    public_key = scalar_multiply(secret, G)

    print(f"  Secret key x:  {_hex_short(secret)}")
    print(f"  Public key X:  ({_hex_short(public_key[0])},")
    print(f"                  {_hex_short(public_key[1])})")

    # Run protocol
    result = run_schnorr_protocol(secret)

    print(f"\n  Step 1 — Prover commits R = r*G:")
    print(f"    R: ({_hex_short(result['R'][0])},")
    print(f"        {_hex_short(result['R'][1])})")

    print(f"\n  Step 2 — Verifier challenges:")
    print(f"    c: {_hex_short(result['challenge'])}")

    print(f"\n  Step 3 — Prover responds:")
    print(f"    s: {_hex_short(result['response'])}")

    print(f"\n  Step 4 — Verification:")
    print(f"    s*G == R + c*X?  {result['valid']}")
    if result['valid']:
        print("    Proof ACCEPTED — prover knows the secret key")
    else:
        print("    Proof REJECTED")

    # --- Demonstrate zero-knowledge property ---
    print("\n--- Zero-Knowledge Property ---\n")
    print("  The verifier learned NOTHING about x except that the prover knows it.")
    print("  The transcript (R, c, s) can be simulated without knowing x:")
    print()

    # Simulate a transcript: pick random s and c, compute R = s*G - c*X
    sim_s = random.SystemRandom().randint(1, N - 1)
    sim_c = random.SystemRandom().randint(1, N - 1)
    sG = scalar_multiply(sim_s, G)
    cX = scalar_multiply(sim_c, public_key)
    # R = s*G - c*X = s*G + (-(c*X))
    neg_cX = (cX[0], (-cX[1]) % P)  # Negate y-coordinate to get -cX
    sim_R = point_add(sG, neg_cX)

    print(f"  Simulated transcript (no secret needed):")
    print(f"    R: ({_hex_short(sim_R[0])},")
    print(f"        {_hex_short(sim_R[1])})")
    print(f"    c: {_hex_short(sim_c)}")
    print(f"    s: {_hex_short(sim_s)}")

    # Verify the simulated transcript
    verifier = SchnorrVerifier(public_key)
    sim_valid = verifier.verify(sim_R, sim_c, sim_s)
    print(f"    Valid? {sim_valid}  (simulated transcripts are indistinguishable!)")

    # --- Show a cheater fails ---
    print("\n--- Soundness: Cheater Without Secret ---\n")

    # A cheater who doesn't know x tries to fake a proof
    fake_x = random.SystemRandom().randint(1, N - 1)  # Wrong secret
    fake_prover = SchnorrProver(fake_x)
    real_verifier = SchnorrVerifier(public_key)  # Verifier has the REAL public key

    R_fake = fake_prover.commit()
    c_real = real_verifier.challenge()
    s_fake = fake_prover.respond(c_real)
    cheat_valid = real_verifier.verify(R_fake, c_real, s_fake)

    print(f"  Cheater uses wrong secret x' != x")
    print(f"  Verification: s*G == R + c*X?  {cheat_valid}")
    print(f"  Proof REJECTED — cheater cannot convince verifier")

    # -----------------------------------------------------------------------
    # Part 2: R1CS Circuit Satisfiability
    # -----------------------------------------------------------------------
    print("\n" + "=" * 70)
    print("  PART 2: R1CS (Rank-1 Constraint System)")
    print("  (Prove you know x satisfying x^2 + x = 42 without revealing x)")
    print("=" * 70)

    print("\n--- Circuit Definition ---\n")
    print("  Problem: Prove knowledge of x where x^2 + x = 42")
    print()
    print("  Arithmetic circuit flattened to R1CS gates:")
    print("  ┌────────────────────────────────────────────────────────┐")
    print("  │  Witness vector: w = [1, x, v1]                      │")
    print("  │  where v1 = x * x (intermediate value)               │")
    print("  │                                                       │")
    print("  │  Gate 1:  (a.w) * (b.w) = (c.w)                      │")
    print("  │           x     *  x    = v1                          │")
    print("  │     a=[0,1,0]  b=[0,1,0]  c=[0,0,1]                  │")
    print("  │                                                       │")
    print("  │  Gate 2:  (a.w) * (b.w) = (c.w)                      │")
    print("  │          (x+v1) *  1    = 42                          │")
    print("  │     a=[0,1,1]  b=[1,0,0]  c=[42,0,0]                 │")
    print("  └────────────────────────────────────────────────────────┘")

    circuit, answer = build_quadratic_circuit()

    # --- Correct witness (x = 6) ---
    print("\n--- Correct Witness (x = 6) ---\n")

    witness_correct = build_witness(answer)
    print(f"  x = {answer}")
    print(f"  x^2 = {answer * answer}")
    print(f"  x^2 + x = {answer * answer + answer}")
    print(f"  Witness: w = {witness_correct}")
    print()

    satisfied, gate_results = circuit.is_satisfied(witness_correct)

    for i, (ok, (a, b, c)) in enumerate(zip(gate_results, circuit.constraints)):
        a_dot_w = dot_product(a + [0] * (len(witness_correct) - len(a)), witness_correct)
        b_dot_w = dot_product(b + [0] * (len(witness_correct) - len(b)), witness_correct)
        c_dot_w = dot_product(c + [0] * (len(witness_correct) - len(c)), witness_correct)
        product = (a_dot_w * b_dot_w) % FP
        print(f"  Gate {i+1}: (a.w={a_dot_w}) * (b.w={b_dot_w}) = {product}")
        print(f"           c.w = {c_dot_w}")
        print(f"           {product} == {c_dot_w}?  {'YES' if ok else 'NO'}")
        print()

    print(f"  All constraints satisfied? {satisfied}")
    if satisfied:
        print("  Proof ACCEPTED — prover knows a valid x")

    # --- Wrong witness (x = 5) ---
    print("\n--- Wrong Witness (x = 5) ---\n")

    wrong_x = 5
    witness_wrong = build_witness(wrong_x)
    print(f"  x = {wrong_x}")
    print(f"  x^2 + x = {wrong_x * wrong_x + wrong_x} (should be 42)")
    print(f"  Witness: w = {witness_wrong}")
    print()

    satisfied_wrong, gate_results_wrong = circuit.is_satisfied(witness_wrong)

    for i, (ok, (a, b, c)) in enumerate(zip(gate_results_wrong, circuit.constraints)):
        a_dot_w = dot_product(a + [0] * (len(witness_wrong) - len(a)), witness_wrong)
        b_dot_w = dot_product(b + [0] * (len(witness_wrong) - len(b)), witness_wrong)
        c_dot_w = dot_product(c + [0] * (len(witness_wrong) - len(c)), witness_wrong)
        product = (a_dot_w * b_dot_w) % FP
        status = "YES" if ok else "NO <-- MISMATCH"
        print(f"  Gate {i+1}: (a.w={a_dot_w}) * (b.w={b_dot_w}) = {product}")
        print(f"           c.w = {c_dot_w}")
        print(f"           {product} == {c_dot_w}?  {status}")
        print()

    print(f"  All constraints satisfied? {satisfied_wrong}")
    print("  Proof REJECTED — wrong witness fails constraint check")

    # --- Another valid solution: x = -7 (mod FP) ---
    print("\n--- Second Valid Solution (x = -7 mod p) ---\n")
    print("  x^2 + x - 42 = 0 has two roots: x=6 and x=-7")
    print(f"  In our field GF({FP}), -7 = {FP - 7}")

    witness_neg7 = build_witness(FP - 7)
    x_neg = FP - 7
    print(f"  x = {x_neg}")
    print(f"  x^2 + x mod p = {(x_neg * x_neg + x_neg) % FP}")
    print(f"  Witness: w = [1, {witness_neg7[1]}, {witness_neg7[2]}]")
    print(f"             (values shown mod p)")

    satisfied_neg, _ = circuit.is_satisfied(witness_neg7)
    print(f"  All constraints satisfied? {satisfied_neg}")
    if satisfied_neg:
        print("  Both roots are valid proofs — R1CS only checks satisfiability")

    # --- Summary ---
    print("\n--- How ZK Proofs Enable Blockchains ---\n")
    print("  ┌────────────────────────────────────────────────────────────┐")
    print("  │  Schnorr Protocol                                        │")
    print("  │    Used in: Schnorr signatures (Bitcoin Taproot),         │")
    print("  │    MuSig multi-signatures, identity proofs                │")
    print("  │                                                           │")
    print("  │  R1CS Circuits                                            │")
    print("  │    Used in: ZK-SNARKs (Zcash, Groth16), ZK-rollups       │")
    print("  │    (zkSync, Polygon zkEVM), verifiable computation        │")
    print("  │                                                           │")
    print("  │  Key Insight: The verifier checks a SHORT proof instead   │")
    print("  │  of re-executing the computation. This is how ZK-rollups  │")
    print("  │  scale blockchains — L1 verifies an L2 proof in O(1).    │")
    print("  └────────────────────────────────────────────────────────────┘")

    print()
    print("=" * 70)
    print("  Zero-Knowledge Proofs complete.")
    print("=" * 70)


# ============================================================================
# SECTION 4: ENTRY POINT
# ============================================================================

if __name__ == "__main__":
    demo()
